"use server";

import { automatedInsuranceClaimDraft } from "@/ai/flows/automated-insurance-claim-draft";
import type { AutomatedInsuranceClaimDraftInput } from "@/ai/flows/automated-insurance-claim-draft";
import { db, doc, collection, writeBatch, serverTimestamp } from "@/lib/firebase";

// submitClaimRequest has been moved to the client-side claims service.

export async function runAutomatedClaim(input: AutomatedInsuranceClaimDraftInput, admin: { uid: string; name: string }) {
  try {
    const result = await automatedInsuranceClaimDraft(input);

    const batch = writeBatch(db);
    const claimRef = doc(db, "claims", input.claimId);
    
    // 1. Update the main claim doc with the AI draft
    batch.update(claimRef, {
        claimDraftText: result.claimDraftText,
        claimDraftJson: result.claimDraftJson,
        status: "inReview", // A more descriptive status after AI drafting
        updatedAt: serverTimestamp(),
        adminId: admin.uid,
    });
    
    // 2. Add history event for drafting
    const historyRef = doc(collection(db, "claims", input.claimId, "history"));
    batch.set(historyRef, {
        action: "drafted",
        by: admin.uid,
        timestamp: serverTimestamp(),
        details: `AI draft generated by admin ${admin.name}.`
    });

    await batch.commit();

    return { success: true, result };
  } catch (error) {
    console.error("Automated Claim failed:", error);
    const message = error instanceof Error ? error.message : "An unknown error occurred.";
    return { success: false, error: `Failed to generate insurance claim draft: ${message}` };
  }
}
